version: '3'
services:
  web-server:
    build: ./webserver
    ports:
      - "8080:80"
    volumes:
      - /webserver/node_modules
      - ./webserver:/webserver
  producer-server:
    build:
      context: .
      dockerfile: ./producer/Dockerfile
    ports:
      - "8081:81"
    volumes:
      - ./producer:/var/www/html
  consumer-server:
    build:
      context: .
      dockerfile: ./consumer/Dockerfile
    ports:
      - "8082:82"
    volumes:
      - ./consumer:/var/www/html
  mysql-db:
    build: ./db/mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=helloprint
    volumes:
      - ./db/mysql/data:/var/lib/mysql
  rabbitmq:
    image: rabbitmq:3.7
    ports:
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest